# Generated by Django 3.1.5 on 2021-01-30 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Job_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_Title', models.CharField(max_length=200)),
                ('site_Logo', models.ImageField(upload_to='media')),
                ('site_background', models.ImageField(null=True, upload_to='media')),
                ('physical_address', models.CharField(blank=True, max_length=500)),
                ('site_Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], default=None, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('self_bio', models.TextField(max_length=150)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status_text', models.TextField(max_length=2000, null=True)),
                ('user_image', models.ImageField(null=True, upload_to='media')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='professional_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(max_length=150)),
                ('professional_Description', models.TextField(max_length=550)),
                ('professional_Experience_level', models.TextField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expart', 'Expart')], max_length=50)),
                ('professional_skills', models.TextField(max_length=550)),
                ('Total_Project', models.IntegerField(default=0)),
                ('Join_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full_time', 'Full_time'), ('Part_time', 'Part_time')], max_length=100)),
                ('Job_introduction', models.CharField(max_length=500)),
                ('Job_thumbnail', models.ImageField(blank=True, null=True, upload_to='media')),
                ('Job_description', models.TextField(max_length=3000)),
                ('Job_requirement', models.TextField(max_length=3000)),
                ('Job_salary_range', models.TextField(max_length=100)),
                ('Job_Location', models.CharField(max_length=1000, null=True)),
                ('Year_of_experience', models.IntegerField()),
                ('job_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_category', models.ManyToManyField(to='mainapp.Job_categories')),
                ('job_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='freelancer_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_title', models.CharField(max_length=200)),
                ('freelancer_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expart', 'Expart')], max_length=100)),
                ('freelancer_thumbnail', models.ImageField(null=True, upload_to='media')),
                ('freelancer_description', models.TextField(max_length=3000)),
                ('freelancer_expected_salary', models.IntegerField()),
                ('freelancer_skills', models.TextField(max_length=3000)),
                ('Year_of_experience', models.IntegerField()),
                ('freelancer_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('freelancer_free_for_work', models.BooleanField(default=False)),
                ('freelancer_promotion', models.BooleanField(default=False)),
                ('freelancer_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
