# Generated by Django 3.1.5 on 2021-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Organization',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
