# Generated by Django 3.1.5 on 2021-01-31 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_freelancer_job_freelancer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Candidates',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
