# Generated by Django 3.1.5 on 2021-01-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210201_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Job_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
