# Generated by Django 3.1.5 on 2021-02-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210201_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer_job',
            name='freelancer_thumbnail',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='user_status',
            name='user_image',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='website_details',
            name='site_Logo',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='website_details',
            name='site_background',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
    ]
