# Generated by Django 3.1.5 on 2021-02-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210202_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='how_to_apply',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
