# Generated by Django 3.1.5 on 2021-02-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210203_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
