# Generated by Django 3.1.5 on 2021-04-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210203_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Organization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
