# Generated by Django 3.1.5 on 2021-04-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
