# Generated by Django 3.1.5 on 2021-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210417_0548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='site_info',
        ),
        migrations.RemoveField(
            model_name='website_details',
            name='physical_address',
        ),
        migrations.AddField(
            model_name='website_details',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='website_details',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='website_details',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
